### ISSUE TITLE
Getting error when I try to install selenium-webdriver-20.7.0.tgz

### ISSUE THREAD

**Issue by alaghu** [aichemydev/selenium-js-examples#5]
[12:46 PM, 10/13/2020] Anand: sorry for my rusty command line knowlege.
[12:47 PM, 10/13/2020] Anand: Should I have to unzip selenium-webdriver-20.7.0.tgz  before I do $>node selenium-webdriver-20.7.0.tgz?
[12:48 PM, 10/13/2020] Anand: When I do $node selenium-webdriver-20.7.0.tgz , I am getting error
[12:48 PM, 10/13/2020] Anand: /Users/Anand/Downloads/selenium-webdriver-20.7.0.tgz:1
�
^

SyntaxError: Invalid or unexpected token

Anand:Downloads/ $ node selenium-webdriver-20.7.0.tgz                [12:45:47]
/Users/Anand/Downloads/selenium-webdriver-20.7.0.tgz:1
�
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by alaghu** [comment]
npm install selenium-webdriver-20.7.0.tgz 


this worked.
